# Generated by Django 5.0 on 2023-12-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamify_Admin', '0002_alter_city_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('game_version', models.CharField(max_length=100)),
                ('game_image', models.CharField(max_length=100)),
                ('game_launch_date', models.DateField()),
                ('game_quantity', models.IntegerField()),
                ('game_description', models.CharField(max_length=500)),
                ('is_available', models.IntegerField(null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamify_Admin.company')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamify_Admin.type')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
    ]
