# Generated by Django 4.2.7 on 2023-12-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamify_Admin', '0004_gamifyuser_user_otp_gamifyuser_user_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
